import json
import subprocess
from pathlib import Path


HYPR_DIR = Path(__file__).resolve().parents[2]
GENERATED_CONFIG = HYPR_DIR / "generated" / "monitors.lua"

COMMON_SCALES = (
    1.0,
    1.25,
    1.5,
    1.75,
    2.0,
)


class DisplayError(RuntimeError):
    pass


def _command(*args):
    result = subprocess.run(
        args,
        text=True,
        capture_output=True,
    )

    if result.returncode != 0:
        message = (
            result.stderr.strip()
            or result.stdout.strip()
            or "Display command failed."
        )

        raise DisplayError(message)

    return result.stdout.strip()


def _normalize_mode(mode):
    return str(mode).removesuffix("Hz")


def _current_mode(monitor):
    return (
        f'{int(monitor["width"])}x'
        f'{int(monitor["height"])}@'
        f'{float(monitor["refreshRate"]):.2f}'
    )


def _monitor_from_json(monitor):
    modes = [
        _normalize_mode(mode)
        for mode in monitor.get(
            "availableModes",
            [],
        )
    ]

    current_mode = _current_mode(
        monitor
    )

    if current_mode not in modes:
        modes.insert(
            0,
            current_mode,
        )

    return {
        "name": monitor["name"],
        "description": (
            monitor.get("description")
            or monitor["name"]
        ),
        "mode": current_mode,
        "modes": modes,
        "x": int(
            monitor.get("x", 0)
        ),
        "y": int(
            monitor.get("y", 0)
        ),
        "scale": float(
            monitor.get("scale", 1.0)
        ),
    }


def get_monitors():
    raw = _command(
        "hyprctl",
        "-j",
        "monitors",
    )

    try:
        payload = json.loads(
            raw
        )
    except json.JSONDecodeError as error:
        raise DisplayError(
            "Hyprland returned invalid monitor data."
        ) from error

    if not isinstance(
        payload,
        list,
    ):
        raise DisplayError(
            "Hyprland returned unexpected monitor data."
        )

    return [
        _monitor_from_json(monitor)
        for monitor in payload
    ]


def _lua_string(value):
    escaped = (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
    )

    return f'"{escaped}"'


def render_config(monitors):
    lines = [
        "-- Generated by Kumina Settings.",
        "-- Changes are replaced when Display settings are applied.",
        "",
    ]

    for monitor in monitors:
        position = (
            f'{monitor["x"]}x'
            f'{monitor["y"]}'
        )

        lines.extend([
            "hl.monitor({",
            (
                "    output = "
                f'{_lua_string(monitor["name"])},'
            ),
            (
                "    mode = "
                f'{_lua_string(monitor["mode"])},'
            ),
            (
                "    position = "
                f'{_lua_string(position)},'
            ),
            (
                "    scale = "
                f'{float(monitor["scale"]):g},'
            ),
            "})",
            "",
        ])

    lines.extend([
        "hl.monitor({",
        '    output = "",',
        '    mode = "preferred",',
        '    position = "auto",',
        '    scale = "auto",',
        "})",
        "",
    ])

    return "\n".join(
        lines
    )


def apply_monitor(
    name,
    mode,
    scale,
):
    monitors = get_monitors()

    target = next(
        (
            monitor
            for monitor in monitors
            if monitor["name"] == name
        ),
        None,
    )

    if target is None:
        raise DisplayError(
            f"Display {name} is no longer available."
        )

    mode = _normalize_mode(
        mode
    )

    if mode not in target["modes"]:
        raise DisplayError(
            "That display mode is no longer available."
        )

    try:
        scale = float(
            scale
        )
    except (
        TypeError,
        ValueError,
    ) as error:
        raise DisplayError(
            "Invalid display scale."
        ) from error

    if not 0.5 <= scale <= 3.0:
        raise DisplayError(
            "Display scale must be between 50% and 300%."
        )

    target["mode"] = mode
    target["scale"] = scale

    GENERATED_CONFIG.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = (
        GENERATED_CONFIG
        .with_suffix(".lua.tmp")
    )

    temporary.write_text(
        render_config(monitors),
        encoding="utf-8",
    )

    temporary.replace(
        GENERATED_CONFIG
    )

    _command(
        "hyprctl",
        "reload",
    )

    return target