import json
import subprocess
from pathlib import Path


HYPR_DIR = Path(__file__).resolve().parents[2]
GENERATED_CONFIG = HYPR_DIR / "generated" / "keyboard.lua"

XKB_RULE_FILES = (
    Path("/usr/share/X11/xkb/rules/base.lst"),
    Path("/usr/share/X11/xkb/rules/evdev.lst"),
)


class KeyboardError(RuntimeError):
    pass


def _command(*args):
    result = subprocess.run(
        args,
        text=True,
        capture_output=True,
    )

    if result.returncode != 0:
        message = (
            result.stderr.strip()
            or result.stdout.strip()
            or "Keyboard command failed."
        )

        raise KeyboardError(message)

    return result.stdout.strip()


def _get_option(name):
    option = f"input.{name}"

    raw = _command(
        "hyprctl",
        "-j",
        "getoption",
        option,
    )

    try:
        return json.loads(raw)
    except json.JSONDecodeError as error:
        raise KeyboardError(
            f"Hyprland returned invalid data for {option}."
        ) from error


def _get_string(name, default=""):
    value = _get_option(name).get("str")

    if not isinstance(value, str):
        return default

    return value


def _get_int(name, default=0):
    value = _get_option(name).get("int")

    if isinstance(value, bool):
        return int(value)

    if not isinstance(value, int):
        return default

    return value


def get_available_layouts():
    rule_file = next(
        (
            path
            for path in XKB_RULE_FILES
            if path.exists()
        ),
        None,
    )

    if rule_file is None:
        return []

    layouts = []
    in_layout_section = False

    for line in rule_file.read_text(
        encoding="utf-8",
        errors="replace",
    ).splitlines():
        stripped = line.strip()

        if stripped.startswith("!"):
            section = stripped[1:].strip()

            if section == "layout":
                in_layout_section = True
                continue

            if in_layout_section:
                break

            continue

        if not in_layout_section or not stripped:
            continue

        parts = stripped.split(
            None,
            1,
        )

        if len(parts) != 2:
            continue

        code, description = parts

        layouts.append({
            "code": code,
            "description": description,
        })

    return layouts


def get_state():
    layout_value = _get_string(
        "kb_layout",
        "fi,us",
    )

    layouts = [
        value.strip()
        for value in layout_value.split(",")
        if value.strip()
    ]

    primary = (
        layouts[0]
        if layouts
        else "fi"
    )

    secondary = (
        layouts[1]
        if len(layouts) > 1
        else None
    )

    return {
        "primary": primary,
        "secondary": secondary,
        "repeat_rate": _get_int(
            "repeat_rate",
            25,
        ),
        "repeat_delay": _get_int(
            "repeat_delay",
            600,
        ),
        "numlock": bool(
            _get_int(
                "numlock_by_default",
                0,
            )
        ),
        "options": _get_string(
            "kb_options",
            "",
        ),
        "available_layouts": (
            get_available_layouts()
        ),
    }


def _lua_string(value):
    escaped = (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
    )

    return f'"{escaped}"'


def _build_options(
    existing,
    has_secondary,
):
    options = [
        option.strip()
        for option in existing.split(",")
        if option.strip()
        and not option.strip().startswith(
            "grp:"
        )
    ]

    if has_secondary:
        options.append(
            "grp:alt_shift_toggle"
        )

    return ",".join(options)


def render_config(
    primary,
    secondary,
    repeat_rate,
    repeat_delay,
    numlock,
    existing_options="",
):
    layout = primary

    if secondary:
        layout += f",{secondary}"

    options = _build_options(
        existing_options,
        bool(secondary),
    )

    return "\n".join([
        "-- Generated by Kumina Settings.",
        "-- Changes are replaced when Keyboard settings are applied.",
        "",
        "return {",
        f"    kb_layout = {_lua_string(layout)},",
        f"    kb_options = {_lua_string(options)},",
        f"    repeat_rate = {int(repeat_rate)},",
        f"    repeat_delay = {int(repeat_delay)},",
        (
            "    numlock_by_default = "
            f'{"true" if numlock else "false"},'
        ),
        "}",
        "",
    ])


def apply_settings(
    primary,
    secondary,
    repeat_rate,
    repeat_delay,
    numlock,
):
    if not primary:
        raise KeyboardError(
            "A primary keyboard layout is required."
        )

    if primary == secondary:
        secondary = None

    repeat_rate = int(
        repeat_rate
    )

    repeat_delay = int(
        repeat_delay
    )

    if not 1 <= repeat_rate <= 100:
        raise KeyboardError(
            "Repeat rate must be between 1 and 100."
        )

    if not 100 <= repeat_delay <= 2000:
        raise KeyboardError(
            "Repeat delay must be between 100 and 2000 ms."
        )

    current_options = _get_string(
        "kb_options",
        "",
    )

    GENERATED_CONFIG.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = (
        GENERATED_CONFIG
        .with_suffix(".lua.tmp")
    )

    temporary.write_text(
        render_config(
            primary,
            secondary,
            repeat_rate,
            repeat_delay,
            numlock,
            current_options,
        ),
        encoding="utf-8",
    )

    temporary.replace(
        GENERATED_CONFIG
    )

    _command(
        "hyprctl",
        "reload",
    )