import json
import subprocess
from pathlib import Path


HYPR_DIR = Path(__file__).resolve().parents[2]
GENERATED_CONFIG = HYPR_DIR / "generated" / "mouse.lua"


class MouseError(RuntimeError):
    pass


def _command(*args):
    result = subprocess.run(
        args,
        text=True,
        capture_output=True,
    )

    if result.returncode != 0:
        message = (
            result.stderr.strip()
            or result.stdout.strip()
            or "Mouse command failed."
        )

        raise MouseError(message)

    return result.stdout.strip()


def _get_option(name):
    option = f"input.{name}"

    raw = _command(
        "hyprctl",
        "-j",
        "getoption",
        option,
    )

    try:
        return json.loads(raw)
    except json.JSONDecodeError as error:
        raise MouseError(
            f"Hyprland returned invalid data for {option}."
        ) from error


def _get_float(
    name,
    default,
):
    value = _get_option(
        name
    ).get("float")

    if isinstance(
        value,
        (int, float),
    ):
        return float(value)

    return default


def _get_bool(
    name,
    default=False,
):
    value = _get_option(
        name
    ).get("int")

    if isinstance(
        value,
        (int, bool),
    ):
        return bool(value)

    return default


def get_state():
    return {
        "sensitivity": _get_float(
            "sensitivity",
            0.0,
        ),
        "natural_scroll": _get_bool(
            "natural_scroll",
            False,
        ),
        "left_handed": _get_bool(
            "left_handed",
            False,
        ),
        "scroll_factor": _get_float(
            "scroll_factor",
            1.0,
        ),
    }


def render_config(
    sensitivity,
    natural_scroll,
    left_handed,
    scroll_factor,
):
    return "\n".join([
        "-- Generated by Kumina Settings.",
        "-- Changes are replaced when Mouse settings are applied.",
        "",
        "return {",
        f"    sensitivity = {sensitivity:g},",
        (
            "    natural_scroll = "
            f'{"true" if natural_scroll else "false"},'
        ),
        (
            "    left_handed = "
            f'{"true" if left_handed else "false"},'
        ),
        f"    scroll_factor = {scroll_factor:g},",
        "}",
        "",
    ])


def apply_settings(
    sensitivity,
    natural_scroll,
    left_handed,
    scroll_factor,
):
    try:
        sensitivity = float(
            sensitivity
        )

        scroll_factor = float(
            scroll_factor
        )
    except (
        TypeError,
        ValueError,
    ) as error:
        raise MouseError(
            "Invalid mouse setting."
        ) from error

    if not -1.0 <= sensitivity <= 1.0:
        raise MouseError(
            "Pointer speed must be between -1.0 and 1.0."
        )

    if not 0.0 <= scroll_factor <= 2.0:
        raise MouseError(
            "Scroll speed must be between 0.0 and 2.0."
        )

    GENERATED_CONFIG.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = (
        GENERATED_CONFIG
        .with_suffix(".lua.tmp")
    )

    temporary.write_text(
        render_config(
            sensitivity,
            natural_scroll,
            left_handed,
            scroll_factor,
        ),
        encoding="utf-8",
    )

    temporary.replace(
        GENERATED_CONFIG
    )

    _command(
        "hyprctl",
        "reload",
    )